[colors.normal]
black = "#000000"
blue = "#12488b"
cyan = "#8abeb7"
green = "#00bb00"
magenta = "#b294bb"
red = "#bb0000"
white = "#dddddd"
yellow = "#f0c674"

[colors.primary]
background = "#000000"
foreground = "#dddddd"

[colors.search.focused_match]
background = "#ffffff"
foreground = "#ff3333"

[colors.search.matches]
background = "#ffffff"
foreground = "#333333"

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.normal]
family = "JetBrainsMonoNL NFM"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Q"
mode = "Vi|~Search"
